In [122]:
import pandas as pd
import numpy as np
import smtplib
from email.message import EmailMessage
import smtplib
import datetime
import os
import requests
import csv

In [2]:
mm = pd.read_csv('megaMillion.csv')
pb = pd.read_csv('powerball.csv')

In [19]:
# 5 nums
mm.iloc[-1,1]

'21 23 33 35 42'

In [20]:
# mega ball
mm.iloc[-1,2]

6

In [27]:
lastest = np.fromstring(mm.iloc[-1,1],dtype=int,sep=' ')
lastest = [21, 23, 33, 35, 42]

In [28]:
mynums = np.array([21, 23, 33, 35, 42])
np.in1d(mynums,lastest)

array([ True,  True,  True,  True,  True])

In [46]:
randomarr = np.random.randint(0,69,size=(1,5))
print(randomarr)
mynums = np.array([21, 23, 33, 35, 42])
match = np.in1d(mynums,randomarr)
match

[[48 44 32 23 32]]


array([False,  True, False, False, False])

read
check
send

In [54]:
matchednum = sum(1 for i in match if i == True)
matchednum

1

## Clean

In [78]:
# my nums 
myfivenums = [12,38,48,52,63]
mymegaball = 10
# Get the new csv
mm = pd.read_csv('megaMillion.csv')

# date
date = mm.iloc[-1,0]
# 5 nums
fivenums = np.fromstring(mm.iloc[-1,1],dtype=int,sep=' ')
# mega ball
megaball = int(mm.iloc[-1,2])

matchingnum = sum(1 for i in (np.in1d(myfivenums, fivenums)) if i == True)

matchingmegaball = mymegaball == megaball

In [112]:
datetime.datetime.now().strftime('%X %x %Z')

'20:42:44 06/17/20 '

## Message

In [115]:
time = datetime.datetime.now().strftime("%X %x %Z")
mainbody = '''
Mega Million
Draw Date: %s 
Five Numbers: %s
My numbers:   %s
Mega Ball:    %i
My Mega Ball: %i
Number of Matched Number: %i
Megal Ball Match: %s 
Sent at %s
'''%(date,fivenums,myfivenums,megaball,mymegaball,matchingnum,matchingmegaball,time,)

mainbody

'\nMega Million\nDraw Date: 06/16/2020 \nFive Numbers: [21 23 33 35 42]\nMy numbers:   [12, 38, 48, 52, 63]\nMega Ball:    6\nMy Mega Ball: 10\nNumber of Matched Number: 0\nMegal Ball Match: False \nSent at 20:45:43 06/17/20 \n'

## Send msg

In [114]:
with smtplib.SMTP('smtp.gmail.com', 587) as smtp:
    smtp.ehlo()
    smtp.starttls()
    smtp.ehlo()

    smtp.login('huangying162000@gmail.com', 'yj20000716')
    subject = 'Mega Millions %s'%(date)

    body = mainbody
    msg = f'subject:{subject} \n\n {body}'
    smtp.sendmail('huangying162000@gmail.com',
                  'yih322+test@lehigh.edu', msg)

# Powerball

In [147]:
powerballURL = ('https://data.ny.gov/api/views/d6yy-54nr/rows.csv')

power = requests.get(powerballURL)

with open('powerball.csv', 'w') as f:
    writer = csv.writer(f)
    for line in power.iter_lines():
        writer.writerow(line.decode('utf-8').split(','))


# Check numbers
# my nums
mynums = [12, 38, 48, 52, 63, 10]
# Get the new csv
pb = pd.read_csv('powerball.csv')
# date
date = pb.iloc[-1, 0]
# 5 nums
nums = np.fromstring(pb.iloc[-1, 1], dtype=int, sep=' ')
# mega ball
powerball = nums[-1]
# check and count matching numbers
matchingnum = sum(1 for i in (np.in1d(mynums, nums)) if i == True)
matchingmegaball = nums[-1] == mynums[-1]

# msg
time = datetime.datetime.now().strftime("%X %x %Z")
mainbody = '''
Powerball
Draw Date: %s 
Winning Numbers: \t%s
My numbers: \t%s
Powerball Ball: \t%i
Number of Matched Number: %i
Powerball Ball Match: %s 
Sent at %s
''' % (date, nums, mynums, powerball, matchingnum, matchingmegaball, time)

In [148]:
mainbody

'\nPowerball\nDraw Date: 06/13/2020 \nWinning Numbers: \t[ 2 12 32 50 65  5]\nMy numbers: \t[12, 38, 48, 52, 63, 10]\nPowerball Ball: \t5\nNumber of Matched Number: 1\nPowerball Ball Match: False \nSent at 21:16:18 06/17/20 \n'

In [144]:
nums[-1]

5